### ISSUE TITLE
Ignore Tags

### ISSUE THREAD

**Issue by lakshag32** [PhotonVision/photonvision#1318]
It would be useful to both our team(and likely others) if we had the ability to ignore certain tags, both in single tag mode and multi-tag mode. If we could ignore tags, we could ignore tags that move around a lot on the field due to robot collisions, improving odometry.

**Comment by mcm001** [comment]
You can already do this, in a roundabout way, by removing tags from the apriltag field layout used or by doing extra processing on-rio to filter single-tag results. Is that enough, and we just need to document it is an option?

**Comment by rwlee** [comment]
@mcm001  -- I think the confusion here is because people expect to be able to reconfigure it in code when there are actually 2 configuration points (rio side and coprocessor side). If you change the `AprilTagFieldLayout` in code, you will have a inconsistency between the rio and coprocessor.

https://docs.photonvision.org/en/latest/docs/apriltag-pipelines/multitag.html#updating-the-field-layout

**Comment by rwlee** [comment]
Also, this seems to effectively be a duplicate issue of #729

**Comment by mcm001** [comment]
Yeah agreed - let's move conversation there
