### ISSUE TITLE
simposeest miscalculating camera pose

### ISSUE THREAD

**Issue by agasser** [PhotonVision/photonvision#499]
The camera pose is being miscalculated in [simposeest example](https://github.com/PhotonVision/photonvision/blob/master/photonlib-java-examples/src/main/java/org/photonlib/examples/simposeest/robot/DrivetrainPoseEstimator.java#L90). Consider when the robot’s rotation is 0° and it is looking directly at a tag, the tag’s known pose on the field is 180°. However, PhotonVision reports the transformation to this tag as -90°.

This is either a bug in PhotonVision beta 3 and the transformation should indicate 180°, or the example needs to subtract 90° from the transformation's rotation:
```
Transform3d camToTarget = target.getCameraToTarget();
  var transform = new Transform2d(
      camToTarget.getTranslation().toTranslation2d(),
      camToTarget.getRotation().toRotation2d().minus(Rotation2d.fromDegrees(90)));

Pose2d camPose = targetPose.transformBy(transform.inverse());
```

**Comment by mcm001** [comment]
The answer is actually a bit weirder than that. We currently report tags with this rotation when facing the camera (see below), which doesn't make a whole lot of sense really. If you see the 3d view in the UI it should match that (Z axis out). 

To make things easier, we've decided to apply a base rotation within photon so that tags are now X facing camera, and Z up, which matches more closely what users expect.

![image](https://user-images.githubusercontent.com/29715865/196065976-c5b1ceb7-68c6-45f1-b210-5a39f595a2af.png)
(before the change)

After #500 gets merged:
![image](https://user-images.githubusercontent.com/29715865/196066041-eb5ed41d-74b7-4c0d-bc37-8998834051be.png)
