### ISSUE TITLE
MemAvailible should be reported rather then MemFree

### ISSUE THREAD

**Issue by sciencewhiz** [PhotonVision/photonvision#771]
Currently the MemFree value appears to be reported from /proc/meminfo. Per the discussion here: https://www.chiefdelphi.com/t/unusually-high-memory-usage-by-wpilib/161864/3 it's better to report MemAvailible rather then MemFree, as the JVM allocates memory for future use that doesn't show as free, but is available.

https://github.com/PhotonVision/photonvision/blob/b1905954bc77acaa16a5475ccf6b5540a89f7328/photon-core/src/main/java/org/photonvision/common/hardware/metrics/cmds/LinuxCmds.java#L35

**Comment by JosephTLockwood** [comment]
"awk '/MemFree:/ {print int($2 / 1000);}' /proc/meminfo;"
"awk '/MemAvailable:/ {print int($2 / 1000);}' /proc/meminfo;"
"sys/class/thermal/thermal_zone1" : For temp (it appears basically any thermal_zone will work)

https://superuser.com/questions/980820/what-is-the-difference-between-memfree-and-memavailable-in-proc-meminfo (For summary)

MemFree: The sum of LowFree+HighFree; The amount of physical RAM, in kilobytes, left unused by the system.


MemAvailable: An estimate of how much memory is available for starting new applications, without swapping. Calculated from MemFree, SReclaimable, the size of the file LRU lists, and the low watermarks in each zone. The estimate takes into account that the system needs some page cache to function well, and that not all reclaimable slab will be reclaimable, due to items being in use. The impact of those factors will vary from system to system.
