### ISSUE TITLE
Calibration intermittently fails

### ISSUE THREAD

**Issue by mcm001** [PhotonVision/photonvision#88]

**Comment by mcm001** [comment]
Except that it doesnt

**Comment by Bankst** [comment]
Reproduced at 320x240 also - @XzibitGG reported it may have something to do with using Point3 to store points.

**Comment by XzibitGG** [comment]
Yeah, object points should contains points in floating point integers instead of doubles, but there does not appear to be a Point3f method instead of Point3 to use. Even then, I think the next step is to see if unit tests pass with equivalent settings and snapshots used to calibrate from the front end.

**Comment by mcm001** [comment]
Even if it doesn't fail, extrinsics often have huge numbers

**Comment by gerth2** [comment]
Is this one still a thing? I've run a number of cal's recently without issue. I hate the 'code works, don't know why' closure issue, but curious if anyone's replicated it recently.
